name: General Report - Histogram of Issues (all)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's code
      - uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub matplotlib

      # Run the script to generate the histogram
      - name: Generate histogram (all issues)
        run: python generate_histogram.py
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Replace with your GitHub Token secret

      # Upload the generated histogram as an artifact
      - name: Upload Histogram
        uses: actions/upload-artifact@v4
        with:
          name: histogram_issues
          path: "*.png"  # This will upload any PNG file generated by the script
